### PR TITLE
Minor wording tweaks

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by jasonblais** [comment]
After this PR, maybe we would release a "v0.1" and upload to community/community-daily servers?

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
I will work on some minor tweaks today. Afterwards I will cut `v0.1`.

**Comment by hanzei** [comment]
I forgot something. We can upload this to community/community-daily right now. The plugin uses bots for posting the messages and they are only available in the `bots` branch. Sorry :disappointed:

**Comment by jasonblais** [comment]
Ah, no worries. @hanzei Can you then help share the January 1 - 31 contributors from all Mattermost repos in my DM? I'll share that with Amy & Lindy.

Once bots are merged we can upload the plugin to community/community-daily :)

**Pull request merged**
