### PR TITLE
add circleci

### PR DESCRIPTION
**Pull request by cpanato**
Based on the dev meeting we are moving to circleci

I did not know this plugin. I will install this on community

### CODE REVIEW

**Review by jasonblais — APPROVED** [review]

**Comment by jasonblais** [comment]
@cpanato We're waiting for bot accounts to be merged to master, after which we can upload this to community. Should be soon :)

**Review by hanzei — CHANGES_REQUESTED** [review]
Let's wait until https://github.com/mattermost/mattermost-plugin-sample/pull/31 is approved and merged.

**Comment by cpanato** [comment]
@hanzei PTAL

**Comment by cpanato** [comment]
in mean time can check the gh status here: https://openfass.azure.k8s.mattermost.com/function/github-stats-page#/ :)

@jasonblais

**Review by hanzei — APPROVED** [review]

**Pull request merged**
